# Generated by Django 4.1.3 on 2023-01-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='money',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
