# Generated by Django 4.1.3 on 2023-01-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_userinfo_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='fullname',
            field=models.CharField(default='Not Mentioned', max_length=100),
        ),
    ]
